const fs = require('fs');
const path = require('path');
const theme = {
  blue_black:
    '--el-border-radius:2.5px; --el-left-menu-width:266px; --el-color-transition:#77e19d; --el-border-radius-base:2.5px; --el-color-info-lighter:#f4f4f5; --el-color-info-light:#e9e9eb; --el-color-error-lighter:#ffeded; --el-color-error-light:#ffdbdc; --el-color-error:#ff4d4f; --el-color-danger-lighter:#ffeded; --el-color-danger-light:#ffdbdc; --el-color-danger:#ff4d4f; --el-color-warning-lighter:#fff8e6; --el-color-warning-light:#fff1cc; --el-color-warning:#ffba00; --el-color-success-lighter:#e7faf0; --el-color-success-light:#d0f5e0; --el-color-success:#13ce66; --el-color-primary-light-9:#e8f4ff; --el-color-primary-light-8:#d1e9ff; --el-color-primary-light-7:#badeff; --el-color-primary-light-6:#a3d3ff; --el-color-primary-light-5:#8cc8ff; --el-color-primary-light-4:#74bcff; --el-color-primary-light-3:#5db1ff; --el-color-primary-light-2:#46a6ff; --el-color-primary-light-1:#2f9bff; --el-color-primary:#1890ff; --el-color-black:#515a6e; --el-color-grey:rgba(0, 0, 0, 0.65)'
  // green_black:
  //   '--el-left-menu-width:266px; --el-color-transition:#1890ff; --el-border-radius-base:2.5px; --el-color-info-lighter:#f4f4f5; --el-color-info-light:#e9e9eb; --el-color-error-lighter:#ffeded; --el-color-error-light:#ffdbdc; --el-color-error:#ff4d4f; --el-color-danger-lighter:#ffeded; --el-color-danger-light:#ffdbdc; --el-color-danger:#ff4d4f; --el-color-warning-lighter:#fff8e6; --el-color-warning-light:#fff1cc; --el-color-warning:#ffba00; --el-color-success-lighter:#e7faf0; --el-color-success-light:#d0f5e0; --el-color-success:#13ce66; --el-color-primary-light-9:#ecf8f3; --el-color-primary-light-8:#d9f0e6; --el-color-primary-light-7:#c6e9da; --el-color-primary-light-6:#b3e1ce; --el-color-primary-light-5:#a0dac2; --el-color-primary-light-4:#8dd3b5; --el-color-primary-light-3:#7acba9; --el-color-primary-light-2:#67c49d; --el-color-primary-light-1:#54bc90; --el-color-primary:#41b584; --el-color-black:#515a6e; --el-color-grey:rgba(0, 0, 0, 0.65); --el-border-radius:2.5px;',
  // purple_white:
  //   '--el-left-menu-width:266px; --el-color-transition:#1890ff; --el-border-radius-base:2.5px; --el-color-info-lighter:#f4f4f5; --el-color-info-light:#e9e9eb; --el-color-error-lighter:#ffeded; --el-color-error-light:#ffdbdc; --el-color-error:#ff4d4f; --el-color-danger-lighter:#ffeded; --el-color-danger-light:#ffdbdc; --el-color-danger:#ff4d4f; --el-color-warning-lighter:#fff8e6; --el-color-warning-light:#fff1cc; --el-color-warning:#ffba00; --el-color-success-lighter:#e7faf0; --el-color-success-light:#d0f5e0; --el-color-success:#13ce66; --el-color-primary-light-9:#f0eefe; --el-color-primary-light-8:#e1ddfc; --el-color-primary-light-7:#d2ccfb; --el-color-primary-light-6:#c3bbf9; --el-color-primary-light-5:#b4aaf8; --el-color-primary-light-4:#a598f6; --el-color-primary-light-3:#9687f5; --el-color-primary-light-2:#8776f3; --el-color-primary-light-1:#7865f2; --el-color-primary:#6954f0; --el-color-black:#515a6e; --el-color-grey:rgba(0, 0, 0, 0.65); --el-border-radius:2.5px;',
  // red_black:
  //   '--el-left-menu-width:266px; --el-color-transition:#ffa194; --el-border-radius-base:2.5px; --el-color-info-lighter:#f4f4f5; --el-color-info-light:#e9e9eb; --el-color-error-lighter:#ffeded; --el-color-error-light:#ffdbdc; --el-color-error:#ff4d4f; --el-color-danger-lighter:#ffeded; --el-color-danger-light:#ffdbdc; --el-color-danger:#ff4d4f; --el-color-warning-lighter:#fff8e6; --el-color-warning-light:#fff1cc; --el-color-warning:#ffba00; --el-color-success-lighter:#e7faf0; --el-color-success-light:#d0f5e0; --el-color-success:#13ce66; --el-color-primary-light-9:#feedeb; --el-color-primary-light-8:#fddbd7; --el-color-primary-light-7:#fbcac3; --el-color-primary-light-6:#fab8af; --el-color-primary-light-5:#f9a69b; --el-color-primary-light-4:#f89487; --el-color-primary-light-3:#f78273; --el-color-primary-light-2:#f5715f; --el-color-primary-light-1:#f45f4b; --el-color-primary:#f34d37; --el-color-black:#515a6e; --el-color-grey:rgba(0, 0, 0, 0.65); --el-border-radius:2.5px;',
  // red_white:
  //   '--el-left-menu-width:266px; --el-color-transition:#ffa194; --el-border-radius-base:2.5px; --el-color-info-lighter:#f4f4f5; --el-color-info-light:#e9e9eb; --el-color-error-lighter:#ffeded; --el-color-error-light:#ffdbdc; --el-color-error:#ff4d4f; --el-color-danger-lighter:#ffeded; --el-color-danger-light:#ffdbdc; --el-color-danger:#ff4d4f; --el-color-warning-lighter:#fff8e6; --el-color-warning-light:#fff1cc; --el-color-warning:#ffba00; --el-color-success-lighter:#e7faf0; --el-color-success-light:#d0f5e0; --el-color-success:#13ce66; --el-color-primary-light-9:#feedeb; --el-color-primary-light-8:#fddbd7; --el-color-primary-light-7:#fbcac3; --el-color-primary-light-6:#fab8af; --el-color-primary-light-5:#f9a69b; --el-color-primary-light-4:#f89487; --el-color-primary-light-3:#f78273; --el-color-primary-light-2:#f5715f; --el-color-primary-light-1:#f45f4b; --el-color-primary:#f34d37; --el-color-black:#515a6e; --el-color-grey:rgba(0, 0, 0, 0.65); --el-border-radius:2.5px;',
  // zihei:
  //   '--el-border-radius:2.5px; --el-left-menu-width:266px; --el-color-transition:#1890ff; --el-border-radius-base:2.5px; --el-color-info-lighter:#f4f4f5; --el-color-info-light:#e9e9eb; --el-color-error-lighter:#ffeded; --el-color-error-light:#ffdbdc; --el-color-error:#ff4d4f; --el-color-danger-lighter:#ffeded; --el-color-danger-light:#ffdbdc; --el-color-danger:#ff4d4f; --el-color-warning-lighter:#fff8e6; --el-color-warning-light:#fff1cc; --el-color-warning:#ffba00; --el-color-success-lighter:#e7faf0; --el-color-success-light:#d0f5e0; --el-color-success:#13ce66; --el-color-primary-light-9:#f0eefe; --el-color-primary-light-8:#e1ddfc; --el-color-primary-light-7:#d2ccfb; --el-color-primary-light-6:#c3bbf9; --el-color-primary-light-5:#b4aaf8; --el-color-primary-light-4:#a598f6; --el-color-primary-light-3:#9687f5; --el-color-primary-light-2:#8776f3; --el-color-primary-light-1:#7865f2; --el-color-primary:#6954f0; --el-color-black:#515a6e; --el-color-grey:rgba(0, 0, 0, 0.65)',
  // green_white:
  //   '--el-border-radius:2.5px; --el-left-menu-width:266px; --el-color-transition:#1890ff; --el-border-radius-base:2.5px; --el-color-info-lighter:#f4f4f5; --el-color-info-light:#e9e9eb; --el-color-error-lighter:#ffeded; --el-color-error-light:#ffdbdc; --el-color-error:#ff4d4f; --el-color-danger-lighter:#ffeded; --el-color-danger-light:#ffdbdc; --el-color-danger:#ff4d4f; --el-color-warning-lighter:#fff8e6; --el-color-warning-light:#fff1cc; --el-color-warning:#ffba00; --el-color-success-lighter:#e7faf0; --el-color-success-light:#d0f5e0; --el-color-success:#13ce66; --el-color-primary-light-9:#ecf8f3; --el-color-primary-light-8:#d9f0e6; --el-color-primary-light-7:#c6e9da; --el-color-primary-light-6:#b3e1ce; --el-color-primary-light-5:#a0dac2; --el-color-primary-light-4:#8dd3b5; --el-color-primary-light-3:#7acba9; --el-color-primary-light-2:#67c49d; --el-color-primary-light-1:#54bc90; --el-color-primary:#41b584; --el-color-black:#515a6e; --el-color-grey:rgba(0, 0, 0, 0.65)',
  // default:
  //   '--el-border-radius:2.5px; --el-left-menu-width:266px; --el-color-transition:#77e19d; --el-border-radius-base:2.5px; --el-color-info-lighter:#f4f4f5; --el-color-info-light:#e9e9eb; --el-color-error-lighter:#ffeded; --el-color-error-light:#ffdbdc; --el-color-error:#ff4d4f; --el-color-danger-lighter:#ffeded; --el-color-danger-light:#ffdbdc; --el-color-danger:#ff4d4f; --el-color-warning-lighter:#fff8e6; --el-color-warning-light:#fff1cc; --el-color-warning:#ffba00; --el-color-success-lighter:#e7faf0; --el-color-success-light:#d0f5e0; --el-color-success:#13ce66; --el-color-primary-light-9:#e8f4ff; --el-color-primary-light-8:#d1e9ff; --el-color-primary-light-7:#badeff; --el-color-primary-light-6:#a3d3ff; --el-color-primary-light-5:#8cc8ff; --el-color-primary-light-4:#74bcff; --el-color-primary-light-3:#5db1ff; --el-color-primary-light-2:#46a6ff; --el-color-primary-light-1:#2f9bff; --el-color-primary:#1890ff; --el-color-black:#515a6e; --el-color-grey:rgba(0, 0, 0, 0.65)'
};
function format(str) {
  const b = str.split(';').filter(item => item);
  const obj = {};
  b.map(item => {
    const d = item.split(':');
    obj[d[0].trim()] = d[1].trim();
  });
  return obj;
}
for (let key in theme) {
  const value = theme[key];
  fs.writeFileSync(
    path.resolve(__dirname, './src/theme', key + '.ts'),
    'export default ' + JSON.stringify(format(value))
  );
}
