export default {
  '--el-border-radius': '2.5px',
  '--el-left-menu-width': '266px',
  '--el-color-transition': '#77e19d',
  '--el-border-radius-base': '2.5px',
  '--el-color-info-lighter': '#f4f4f5',
  '--el-color-info-light': '#e9e9eb',
  '--el-color-error-lighter': '#ffeded',
  '--el-color-error-light': '#ffdbdc',
  '--el-color-error': '#ff4d4f',
  '--el-color-danger-lighter': '#ffeded',
  '--el-color-danger-light': '#ffdbdc',
  '--el-color-danger': '#ff4d4f',
  '--el-color-warning-lighter': '#fff8e6',
  '--el-color-warning-light': '#fff1cc',
  '--el-color-warning': '#ffba00',
  '--el-color-success-lighter': '#e7faf0',
  '--el-color-success-light': '#d0f5e0',
  '--el-color-success': '#13ce66',
  '--el-color-primary-light-9': '#e8f4ff',
  '--el-color-primary-light-8': '#d1e9ff',
  '--el-color-primary-light-7': '#badeff',
  '--el-color-primary-light-6': '#a3d3ff',
  '--el-color-primary-light-5': '#8cc8ff',
  '--el-color-primary-light-4': '#74bcff',
  '--el-color-primary-light-3': '#5db1ff',
  '--el-color-primary-light-2': '#46a6ff',
  '--el-color-primary-light-1': '#2f9bff',
  '--el-color-primary': '#1890ff',
  '--el-color-black': '#515a6e',
  '--el-color-grey': 'rgba(0, 0, 0, 0.65)'
};
