export default {
  '--el-left-menu-width': '266px',
  '--el-color-transition': '#ffa194',
  '--el-border-radius-base': '2.5px',
  '--el-color-info-lighter': '#f4f4f5',
  '--el-color-info-light': '#e9e9eb',
  '--el-color-error-lighter': '#ffeded',
  '--el-color-error-light': '#ffdbdc',
  '--el-color-error': '#ff4d4f',
  '--el-color-danger-lighter': '#ffeded',
  '--el-color-danger-light': '#ffdbdc',
  '--el-color-danger': '#ff4d4f',
  '--el-color-warning-lighter': '#fff8e6',
  '--el-color-warning-light': '#fff1cc',
  '--el-color-warning': '#ffba00',
  '--el-color-success-lighter': '#e7faf0',
  '--el-color-success-light': '#d0f5e0',
  '--el-color-success': '#13ce66',
  '--el-color-primary-light-9': '#feedeb',
  '--el-color-primary-light-8': '#fddbd7',
  '--el-color-primary-light-7': '#fbcac3',
  '--el-color-primary-light-6': '#fab8af',
  '--el-color-primary-light-5': '#d7a69b',
  '--el-color-primary-light-4': '#d29487',
  '--el-color-primary-light-3': '#af384f',
  '--el-color-primary-light-2': '#a8354b',
  '--el-color-primary-light-1': '#a23146',
  '--el-color-primary-dark-2': '#972c3f',
  '--el-color-primary': '#A02F43',
  '--el-color-black': '#515a6e',
  '--el-color-grey': 'rgba(0, 0, 0, 0.65)',
  '--el-border-radius': '2.5px'
};
