export default {
  '--el-left-menu-width': '266px',
  '--el-color-transition': '#1890ff',
  '--el-border-radius-base': '2.5px',
  '--el-color-info-lighter': '#f4f4f5',
  '--el-color-info-light': '#e9e9eb',
  '--el-color-error-lighter': '#ffeded',
  '--el-color-error-light': '#ffdbdc',
  '--el-color-error': '#ff4d4f',
  '--el-color-danger-lighter': '#ffeded',
  '--el-color-danger-light': '#ffdbdc',
  '--el-color-danger': '#ff4d4f',
  '--el-color-warning-lighter': '#fff8e6',
  '--el-color-warning-light': '#fff1cc',
  '--el-color-warning': '#ffba00',
  '--el-color-success-lighter': '#e7faf0',
  '--el-color-success-light': '#d0f5e0',
  '--el-color-success': '#13ce66',
  '--el-color-primary-light-9': '#ecf8f3',
  '--el-color-primary-light-8': '#d9f0e6',
  '--el-color-primary-light-7': '#c6e9da',
  '--el-color-primary-light-6': '#b3e1ce',
  '--el-color-primary-light-5': '#a0dac2',
  '--el-color-primary-light-4': '#8dd3b5',
  '--el-color-primary-light-3': '#7acba9',
  '--el-color-primary-light-2': '#67c49d',
  '--el-color-primary-light-1': '#54bc90',
  '--el-color-primary-dark-2': '#059963',
  '--el-color-primary': '#41b584',
  '--el-color-black': '#515a6e',
  '--el-color-grey': 'rgba(0, 0, 0, 0.65)',
  '--el-border-radius': '2.5px'
};
