name: Build & Push Docker

on:
  push:
    branches:
      - master

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
      # - name: Check Secrets
      #   run: |
      #     if [ -z "${{ secrets.ALIYUN_USERNAME }}" ]; then
      #       echo "USERNAME is EMPTY"
      #     else
      #       echo "USERNAME OKK"
      #     fi
      
      #     if [ -z "${{ secrets.ALIYUN_PASSWORD }}" ]; then
      #       echo "PASSWORD is EMPTY"
      #     else
      #       echo "PASSWORD OK"
      #     fi
      
      #     if [ -z "${{ secrets.ALIYUN_REGISTRY }}" ]; then
      #       echo "REGISTRY is EMPTY"
      #     else
      #       echo "REGISTRY OK"
      #     fi
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      # 登录阿里云镜像仓库
      - name: Login Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      # 读取 Version
      - name: Read Server Version
        id: vane
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      # Build Server
      - name: Build Server
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: |
            crpi-vit1t6doo4kal24v.cn-beijing.personal.cr.aliyuncs.com/big0range-demo/vane-server:${{ steps.vane.outputs.VERSION }}
            crpi-vit1t6doo4kal24v.cn-beijing.personal.cr.aliyuncs.com/big0range-demo/vane-server:latest

      # Build Client
      - name: Build Client
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.nginx
          push: true
          tags: |
            crpi-vit1t6doo4kal24v.cn-beijing.personal.cr.aliyuncs.com/big0range-demo/vane-nginx:${{ steps.vane.outputs.VERSION }}
            crpi-vit1t6doo4kal24v.cn-beijing.personal.cr.aliyuncs.com/big0range-demo/vane-nginx:latest
